# This is for cross-domain experiments using DrugBAN with domain adaptation.

DATA:
  DATASET: "bindingdb" # bindingdb, biosnap
  SPLIT: "cluster"

SOLVER:
  BATCH_SIZE: 32
  MAX_EPOCH: 2
  LEARNING_RATE: 1e-4
  DA_LEARNING_RATE: 5e-5
  SEED: 42

DA:
  TASK: True
  USE: True
  METHOD: "CDAN"
  USE_ENTROPY: False
  RANDOM_LAYER: True
  ORIGINAL_RANDOM: True
  RANDOM_DIM: 256
  INIT_EPOCH: 10

DECODER:
  BINARY: 2

# Config below only when you use comet
COMET:
  PROJECT_NAME: "DrugBAN_CDAN"
  TAG: "DA"

RESULT:
  OUTPUT_DIR: "./result_DA"
