# This is for in-domain experiments using DrugBAN without domain adaptation.

DATA:
  DATASET: "bindingdb"  # bindingdb, biosnap, human
  SPLIT: "random"       # random, cold

SOLVER:
  BATCH_SIZE: 64
  MAX_EPOCH: 100
  LEARNING_RATE: 5e-5
  SEED: 42

DA:
  TASK: False
  USE: False

DECODER:
  BINARY: 1

# Config below only when you use comet
COMET:
  PROJECT_NAME: "DrugBAN_Vanilla"
  TAG: "Non_DA"
